In [18]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
df = pd.read_csv('../../data/100_sentiment_analysis_sentences.csv')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    100 non-null    object
 1   label   100 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB


In [30]:
# replacing values
df['label'].replace(['POSITIVE', 'NEGATIVE', 'NEUTRAL'],
                        [2, 0,1], inplace=True)

In [31]:
tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5,
                        ngram_range=(1, 2), 
                        stop_words='english')

# We transform each complaint into a vector
features = tfidf.fit_transform(df.text)

labels = df.label

print("Each of the %d label is represented by %d features (TF-IDF score of unigrams and bigrams)" %(features.shape))

Each of the 100 label is represented by 61 features (TF-IDF score of unigrams and bigrams)


In [32]:
df_tfidf = pd.DataFrame(features.toarray(), columns=tfidf.get_feature_names(), index=df.index)
df_tfidf['label'] = df['label']
df_tfidf.head()
df_tfidf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 62 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   2030               100 non-null    float64
 1   2035               100 non-null    float64
 2   access             100 non-null    float64
 3   access reuters     100 non-null    float64
 4   agency             100 non-null    float64
 5   battery            100 non-null    float64
 6   black              100 non-null    float64
 7   brand              100 non-null    float64
 8   california         100 non-null    float64
 9   car                100 non-null    float64
 10  carb               100 non-null    float64
 11  com                100 non-null    float64
 12  com register       100 non-null    float64
 13  company            100 non-null    float64
 14  department         100 non-null    float64
 15  did                100 non-null    float64
 16  electric           100 non-

In [33]:
features.shape

(100, 61)

In [34]:
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Bidirectional,Dropout,LSTM

In [35]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(features.shape[1],), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))
# compile the keras model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [36]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 12)                744       
                                                                 
 dense_7 (Dense)             (None, 8)                 104       
                                                                 
 dense_8 (Dense)             (None, 3)                 27        
                                                                 
Total params: 875
Trainable params: 875
Non-trainable params: 0
_________________________________________________________________


In [37]:
type(features)

scipy.sparse.csr.csr_matrix

In [38]:
# fit the keras model on the dataset
model.fit(features.toarray(), labels, epochs=10, batch_size=10)
# evaluate the keras model
_, accuracy = model.evaluate(features.toarray(), labels)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/10


InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\traitlets\config\application.py", line 978, in launch_instance
      app.start()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\asyncio\base_events.py", line 570, in run_forever
      self._run_once()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\asyncio\base_events.py", line 1859, in _run_once
      handle._run()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\asyncio\events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
      res = shell.run_cell(
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_cell
      result = self._run_cell(
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\IPython\core\interactiveshell.py", line 2936, in _run_cell
      return runner(coro)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\IPython\core\interactiveshell.py", line 3135, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\IPython\core\interactiveshell.py", line 3338, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\metes\AppData\Local\Temp\ipykernel_38336\3225703028.py", line 2, in <cell line: 2>
      model.fit(features.toarray(), labels, epochs=10, batch_size=10)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\training.py", line 994, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\training.py", line 1052, in compute_loss
      return self.compiled_loss(
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\losses.py", line 152, in __call__
      losses = call_fn(y_true, y_pred)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\losses.py", line 272, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\losses.py", line 2084, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "c:\Users\metes\Anaconda3\envs\sentiment_analysis_api\lib\site-packages\keras\backend.py", line 5630, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
Received a label value of 111 which is outside the valid range of [0, 3).  Label values: 22 0 22 22 111 22 22 0 111 0
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_4267]

In [ ]:
model.predict(features[0].toarray())

1/1 [==============================] - 0s 235ms/step


array([[0.33746785, 0.31244713, 0.35008496]], dtype=float32)

In [ ]:
features[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.61294011, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70746152, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.35185596, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [39]:
import pickle
model.save("../models/tfidf_custom_dl_keras")
pickle.dump(tfidf, open("../models/tfidf_vectorizer_custom_dl_keras.pkl", "wb"))

INFO:tensorflow:Assets written to: ../models/tfidf_custom_dl_keras\assets


In [40]:
import keras
saved_model = keras.models.load_model("../models/tfidf_custom_dl_keras")
saved_tfidf =  pickle.load(open('../models/tfidf_vectorizer_custom_dl_keras.pkl', 'rb'))

In [41]:
#Inference Code
test_input = saved_tfidf.transform(["test_input"]).toarray()
new_prediction = saved_model.predict(test_input)
print(new_prediction)
predicted_class_id = new_prediction.argmax().item()
print(predicted_class_id)

1/1 [==============================] - 0s 91ms/step
[[0.33333334 0.33333334 0.33333334]]
0
